### ISSUE TITLE
Need some new textures

### ISSUE THREAD

**Issue by dmf444** [xbony2/Nuclear-Control#100]
@Pyrolusite :

I made a remote monitor, works like the Info Panel except is an item that you can walk with.
If you can make an item texture for it, that would be great, as well as if you redid my GUI to fit the style more. (https://github.com/xbony2/Nuclear-Control/blob/dmf444/src/main/resources/assets/nuclearcontrol/textures/gui/GUIRemoteMonitor.png)

**Comment by Pyrolusite** [comment]
Noted, will work on it.

**Comment by Pyrolusite** [comment]
So, yeah, sorry for the delay, didn't forget you all, will work on it asap.

Also, related to the GUI, you want something closer to NC2 standard ones ?

**Comment by xbony2** [comment]
Sort of IC2-ish I guess, there's not much of NC2 standard for GUIs.

**Comment by Pyrolusite** [comment]
Okay, currently working on them.

Last question : Is the "Remote Monitor Card" supposed to fit on the "Remote Monitor" icon or something like the other cards should be fine ?

**Comment by Pyrolusite** [comment]
Textures done. I didn't really see any improvements I could make to the Remote Monitor GUI, so I changed somme little things here and there but that's it.
Open the issue again if you need something changed.

**Comment by xbony2** [comment]
Looks good to me ^_^
