### ISSUE TITLE
Please refer to net.minecraftforge.oredict.RecipeSorter

### ISSUE THREAD

**Issue by bookerthegeek** [xbony2/Nuclear-Control#101]
````
[22:26:00] [Client thread/INFO] [FML]:   Unknown recipe class! shedar.mods.ic2.nuclearcontrol.StorageArrayRecipe Modder please refer to net.minecraftforge.oredict.RecipeSorter
````
Repost from: MyM-ModpackTeam/B2B#6

Weirdly enough it says shedar on there making me think of going https://bitbucket.org/shedar/ic2-nuclear-control/ But this Github is where the IC2 forum post links me to. Sorry if this is the incorrect place to post.

**Comment by xbony2** [comment]
Right place, yes. Shedar is the original creator of the mod. I'm the unofficial maintainer (but I'm mostly lazy nowadays).

**Comment by Adaptivity** [comment]
I can fix this :) Later today probably

**Comment by bookerthegeek** [comment]
Thank you. Probably was not game breaking, I just hate red in my logs. Muahaha
