### ISSUE TITLE
Classic Support (Info)

### ISSUE THREAD

**Issue by Speiger** [xbony2/Nuclear-Control#106]
I am working on a IC2 Classic Port atm (right now while i write this message)
So please wait for my push as long as i try to make functions and stuff compatible.
It will also support the steam reactor.
Just a question: i will require the class ISteamReactor, but it is only in the Classic API so what should i do?

**Comment by xbony2** [comment]
Reflection. I'll try to see if I can mess around with #107 in this instance.

**Comment by Speiger** [comment]
Would be cool. It is the patch which is compatible with the version which comes out today/tomorrow...
So would be cool if it is then compatible and all that stuff.
