### ISSUE TITLE
Large RF storage support

### ISSUE THREAD

**Issue by MRuth** [xbony2/Nuclear-Control#115]
Would it be possible to add support for displaying correct information for large RF storage mechanisms, such as Mekanism's Induction Matrix, a multiblock RF storage device?  It seems that the Energy Storage kit and the Advanced Information panels are able to read it, but display incorrect information, possibly due to maximum datatype limits..

Here are some screenshots of using the latest betra with the Induction Matrix.

![2015-10-08_21 59 54](https://cloud.githubusercontent.com/assets/3927478/10384961/749c588e-6e08-11e5-977c-9dd276573460.png)
![2015-10-08_21 59 47](https://cloud.githubusercontent.com/assets/3927478/10384960/7499b840-6e08-11e5-9c73-7f070cb4fc2a.png)

**Comment by dmf444** [comment]
Working on it... Mekanism has decided to use a value extremely large relative to other mods, so this has to be another crossmod intergration

**Comment by dmf444** [comment]
Leave a comment

**Comment by bookerthegeek** [comment]
Would you also be able to add in support for the draconic evolution energy ball, and also the batteries from electicraft?

Links

http://www.brandon3055.com/draconic-evolution/energy-core-multi-block/

https://sites.google.com/site/reikasminecraft/electricraft

**Comment by xbony2** [comment]
Does the energy core not work?

**Comment by bookerthegeek** [comment]
Hm. This was in regards to the large numbers, not specifically if it worked or not. As the energy core can hold max integer of rf I assumed it also might have the same issue. Sorry if not an issue as I'm at work and can't check till I get home.

**Comment by xbony2** [comment]
I just think it might already work. I'd like it if you/someone tested it though (I would myself, but I really don't know DE).

**Comment by dmf444** [comment]
It probably won't. DE implements a long as its extended storage. We only have a wrapper for Mek's Double. I can look into implementing it, but for now Mek and standard RF is covered.

**Comment by bookerthegeek** [comment]
Got a list of any other mods with massive storage?  I'll test them tonight, along with a couple other things.
