### ISSUE TITLE
"Time to cycle end" broken after updating

### ISSUE THREAD

**Issue by Forecaster** [xbony2/Nuclear-Control#118]
After updating from 2.2.1a to 2.3.1a the time remaining now displays 0:00:00 all the time.

This is a fluid cooled reactor where I'm using one card activated on the inner reactor (to get the fuel time) and one card activated on the casing to get the fluid reactor info.

Before the update the time display worked as expected.

**Comment by dmf444** [comment]
Need more info... Possible pics? Not sure what your set up is, but I just tested this and it works for me

**Comment by Forecaster** [comment]
Here, this is me explaining my problem:
https://www.youtu.be/JG9_TT0Gg3w

**Comment by Forecaster** [comment]
Forgot to set the video to unlisted.

**Comment by dmf444** [comment]
Still can't see the video...

**Comment by Forecaster** [comment]
This link should work: https://youtu.be/JG9_TT0Gg3w

**Comment by Forecaster** [comment]
And there is no voice in the video...
-_-

**Comment by Forecaster** [comment]
This works again after updating 2.3.1a => 2.3.3a
