### ISSUE TITLE
Dupe bug in Advanced Information Panel

### ISSUE THREAD

**Issue by artubi** [xbony2/Nuclear-Control#125]
Hi,
Cards can be duplicated in Advanced Information Panel.

Using:
IC2NuclearControl-2.3.2a-Butt

Steps to reproduce:
1. Use 2 different cards, for example Time and Text 
2. Place Text card into first card slot in Advanced Information Panel
3. Pickup Time card and try to place it into first slot
4. Text card has changed into time card

It does work with any cards. Works only in first card slot. Second and third slots aren't affected.

**Comment by dmf444** [comment]
Must  override transferStackInSlot
