### ISSUE TITLE
Compatibility issue with AE2rv3 (crash on player join)

### ISSUE THREAD

**Issue by Xiaminou** [xbony2/Nuclear-Control#128]
in my modpack with 258 mods, crash when I join my server with a world with alot of stuff in it.

Singleplayer in a new world works fine.

Crash Report: http://pastebin.com/hF3qwrzV

**Comment by walkerjonny** [comment]
I double that. Happens with the newest AE2 rv3 alpha 10.
http://pastebin.com/XqT20miZ

**Comment by dmf444** [comment]
Line 43 and line 129, must change to getGridProxy or something close to that.
