### ISSUE TITLE
Curse isn't aware IC2 is required

### ISSUE THREAD

**Issue by natedogith1** [xbony2/Nuclear-Control#130]
It seems IC2 isn't registered as a dependency in Curse.

**Comment by liach** [comment]
Because this can depend on multiple versions of industrial crafts.

**Comment by natedogith1** [comment]
that's not what the dependency list says (https://github.com/xbony2/Nuclear-Control/blob/master/src/main/java/shedar/mods/ic2/nuclearcontrol/IC2NuclearControl.java#L40)

**Comment by xbony2** [comment]
Um, I'm not sure why this is being reported to me :P IC2 isn't on CurseForge.

**Comment by natedogith1** [comment]
Yeah, sorry, I forgot that was a thing, and I was running into so many mods that had I similar problem, I didn't even think to check.
