### ISSUE TITLE
I do even want to start

### ISSUE THREAD

**Issue by Speiger** [xbony2/Nuclear-Control#132]
https://github.com/xbony2/Nuclear-Control/blob/master/src/main/java/shedar/mods/ic2/nuclearcontrol/tileentities/TileEntityThermo.java#L219
.... Exp api is more then enough... Please change that to IReactor instead of a Exp Releated only Class which i can not support...

**Comment by dmf444** [comment]
That change was made because using IReactor would crash the game. From what I can tell, a 5x5x5 reactor does not cast to IReactor. See #114 for crash and reason for revert

**Comment by Speiger** [comment]
why are you checking the chamber which has no logic at all.... Also this causes incompatiblity with classic......

**Comment by dmf444** [comment]
The chamber exposes the functions needed for the panel. Does Classic have a 5x5x5 reactor? If so, does it all cast from IReactor?

**Comment by Speiger** [comment]
ok. All the reflection part was on my side a bad idea. I agree with that. But still everything is accessable through the API:
https://github.com/xbony2/Nuclear-Control/blob/e82a22933dcfa5b3531156017e4e1b23d205bbed/src/main/java/shedar/mods/ic2/nuclearcontrol/items/ItemCard55Reactor.java
Line 54: can be returned through IReactor: produceEnergy()
Line 55-56: Cast it as a IFluidHandler and get the fluidTank info. first tank you get is the input tank second is the output.
Only thing where you require Exp is simply the EmitHeat...
But for that you could use a Proxy which prevents Exps Data to coilide with classic...

**Comment by Speiger** [comment]
the 5x5x5 is just a normal reactor with a casing no code change... Its still the basic reactor... And yeah IC2 Classic supports IReactor without any problems as the 5x5x5 reactor from Ic2Exp... Just that it is a normal reactor with a casing... Its still uses the IReactor API...

**Comment by dmf444** [comment]
i'll try to patch in something, I have an idea of how to do them both
