### ISSUE TITLE
Crash with IC2 Classic and Nuclear Control

### ISSUE THREAD

**Issue by Speiger** [xbony2/Nuclear-Control#133]
Someone messaged me in the IC2 Forums with the following text:
Ic2 Classic & Tekkit Legends Server Crash Help
Hiya, im having a problem on my server. It keeps restarting every few minutes with the following error. Any ideas what I can do to fix this?

http://pastebin.com/eY3ghCAw

Note from the pastebin it is clear that this is not a fault on IC2 Classic (and yeah i know that there are package problems) but could you fix that problem please?

**Comment by dmf444** [comment]
You've fixed this in your PR, right?

**Comment by Speiger** [comment]
If you readed it then you know the answer...
If not:
(Short version for of it : NC code is horrible as death and i fixed that problem)

**Comment by dmf444** [comment]
Leave a comment
