### ISSUE TITLE
Crash when placing thermal monitor 1 block away from reactor

### ISSUE THREAD

**Issue by Nentify** [xbony2/Nuclear-Control#135]
http://pastebin.com/gmUkR9S6

To reproduce:

- Use latest IC2 Classic and Nuclear Control
- Place a nuclear reactor
- Place a block next to the reactor
- Place thermal monitor on the block

Screenshot (place on red part): http://i.imgur.com/fr31ZY7.png
Before crash: http://i.imgur.com/9X99fx8.png

**Comment by dmf444** [comment]
Known issue, thanks for reporting. #134 will fix it when accepted.

**Comment by dmf444** [comment]
Leave a comment
