### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by OvermindDL1** [xbony2/Nuclear-Control#142]
Fresh download fails compilation with error:
```
/home/overminddl1/Minecraft/GT5u/Nuclear-Control/build/sources/java/shedar/mods/ic2/nuclearcontrol/crossmod/appeng/TileEntityNetworkLink.java:96: error: cannot access IStrictEnergyAcceptor
                ItemStack is = chest.getInternalInventory().getStackInSlot(0);
                                    ^
  class file for mekanism.api.energy.IStrictEnergyAcceptor not found
```
The build had no issues with downloading dependencies and no other relevant warnings were shown.

**Comment by xbony2** [comment]
Yeah, I have the same issue every time I try to compile it. Releases are built on [drone.io](https://drone.io/github.com/xbony2/Nuclear-Control/files).

**Comment by OvermindDL1** [comment]
After delving into the compilation structure it looks like it is an AE bug...  Is that right?  o.O

**Comment by xbony2** [comment]
Well, if I recall correctly this is issue was introduced in one of AE2's updates.

**Comment by OvermindDL1** [comment]
Not surprising.  You can change your deps to require a certain known-working version of AE2 as a workaround instead of using one in the lib directory (AE2 used to have maven dep support, does it not still?!), as long as the API is the same then people will still be able to use this mod with the latest AE2 as well.  How do you compile it?  If it can be figured out how to clean compile it after straight download with `gradle compile` then I can add it to the forge build server for automatic compilation and insertion into the forge maven.

**Comment by dmf444** [comment]
The problem with that switching versions is that I actually call functions and classes not in the API, forcing a dependency on the newest version of the mod. I believe they do have a maven, we just don't use it.
