### ISSUE TITLE
OpenComputers can't completely rotate (Advanced) Info Panels

### ISSUE THREAD

**Issue by MyNameIsKodos** [xbony2/Nuclear-Control#144]
Rotating an info panel manually sets it to 56, according to OpenComputers, but the function to rotate it via OpenComputers only accepts a value of 1 through 16, thus only allowing for a small amount of rotation via computer vs doing it manually

**Comment by xbony2** [comment]
How does OpenComputers rotate things?

**Comment by MyNameIsKodos** [comment]
First, you need to hook up an Info Panel via an OC Adapter like so:
![Info Panel Component](http://puu.sh/nQVes/1bc09773f6.png)

Note how it's rotated all the way? I did that manually via the Info Panel's rotation settings tab.

Now, see here, how I've called getRotationHorizontally() which should return the value that the panel is currently rotated at:
![getRotation](http://puu.sh/nQVj0/c72af1bf8a.png)

But if you look at the function info, it only accepts a value of 1-16, which means I can only rotate it the equivalent of two notches on the settings tab, and I can only rotate it in a positive manner, since it won't take a negative number for the rotation settings:
![Screenshot 3](http://puu.sh/nQVn9/e1b70febb2.png)

**Comment by MyNameIsKodos** [comment]
Closing since it's been nearly 2 years with no comment/resolution
