### ISSUE TITLE
Crash on startup (w. master)

### ISSUE THREAD

**Issue by xbony2** [xbony2/Nuclear-Control#147]
~~~~
[11:38:41] [Client thread/ERROR] [FML]: Caught exception from Mekanism
java.lang.NoClassDefFoundError: codechicken/multipart/BlockMultipart
~~~~
Merp.

[Not really caused by us]

**Comment by dmf444** [comment]
Easy to fix: either add Forge Multipart dev jar to eclipse/mods or add to build.gradle and compile with it. Let me know what you want me to do
