### ISSUE TITLE
Need Textures for new Cards

### ISSUE THREAD

**Issue by dmf444** [xbony2/Nuclear-Control#151]
New card types:
-Vanilla Machines (Brewing stand and Furnace)
-Vanilla Machine Kit

paging @Pyrolusite 
basically, last thing prior to 1.7.10 final release (I think)

**Comment by Pyrolusite** [comment]
Noted, will work on it asap.

**Comment by xbony2** [comment]
Final-ish. It is possible there will need to be a few bug updates.

**Comment by Pyrolusite** [comment]
#152 Done.

**Comment by xbony2** [comment]
I like how it looks vanilla :P

**Comment by dmf444** [comment]
Thank you!
