### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by linkinkov** [xbony2/Nuclear-Control#162]
---- Minecraft Crash Report ----
// Oops.

Time: 05/07/16 21:19
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
    at shedar.mods.ic2.nuclearcontrol.containers.ContainerEmpty.func_75145_c(ContainerEmpty.java:21)
    at net.minecraftforge.event.entity.player.PlayerOpenContainerEvent.<init>(PlayerOpenContainerEvent.java:27)
    at net.minecraftforge.common.ForgeHooks.canInteractWith(ForgeHooks.java:448)
    at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:319)
    at net.minecraft.world.World.func_72866_a(World.java:2696)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877)
    at net.minecraft.world.World.func_72870_g(World.java:2645)
    at net.minecraft.world.World.func_72939_s(World.java:2447)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at shedar.mods.ic2.nuclearcontrol.containers.ContainerEmpty.func_75145_c(ContainerEmpty.java:21)
    at net.minecraftforge.event.entity.player.PlayerOpenContainerEvent.<init>(PlayerOpenContainerEvent.java:27)
    at net.minecraftforge.common.ForgeHooks.canInteractWith(ForgeHooks.java:448)
    at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:319)
    at net.minecraft.world.World.func_72866_a(World.java:2696)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:877)
    at net.minecraft.world.World.func_72870_g(World.java:2645)

-- Entity being ticked --
Details:
    Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
    Entity ID: 468957
    Entity Name: BoJI9
    Entity's Exact location: -1107.32, 49.00, -2034.89
    Entity's Block location: World: (-1108,49,-2035), Chunk: (at 12,3,13 in -70,-128; contains blocks -1120,0,-2048 to -1105,255,-2033), Region: (-3,-4; contains chunks -96,-128 to -65,-97, blocks -1536,0,-2048 to -1025,255,-1537)
    Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:2447)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)

-- Affected level --
Details:
    Level name: world
    All players: 21 total; [EntityPlayerMP['Dominig12'/9741, l='world', x=-2649.29, y=69.00, z=-2641.32](Dominig12 at -2649.2880974628215,69.0,-2641.322918609913), EntityPlayerMP['4Mir'/8596, l='world', x=-2630.21, y=72.00, z=-2618.50](4Mir at -2630.210238929766,72.0,-2618.5030594572454), EntityPlayerMP['AppleBoy'/6594, l='world', x=-1107.86, y=49.00, z=-2039.70](AppleBoy at -1107.8590525925608,49.0,-2039.699999988079), EntityPlayerMP['oSlIk'/207409, l='world', x=-2646.26, y=76.00, z=-4822.92](oSlIk at -2646.258043963133,76.0,-4822.920616238591), EntityPlayerMP['DarkGuard'/395827, l='world', x=-2632.84, y=73.00, z=-2673.67](DarkGuard at -2632.840346960754,73.0,-2673.6660933952976), EntityPlayerMP['DJoniFX'/415459, l='world', x=-1774.65, y=70.00, z=-307.25](DJoniFX at -1774.6504534072867,70.0,-307.2541469054957), EntityPlayerMP['veber'/389876, l='world', x=-2047.69, y=69.00, z=-1457.00](veber at -2047.6889925027995,69.0,-1457.0040799559047), EntityPlayerMP['nistyak'/439307, l='world', x=-361.66, y=67.00, z=-373.83](nistyak at -361.6643500990588,67.0,-373.8302597416558), EntityPlayerMP['BoJI9'/468957, l='world', x=-1107.32, y=49.00, z=-2034.89](BoJI9 at -1107.3176942649088,49.0,-2034.8866930742633), EntityPlayerMP['shiken'/491653, l='world', x=-1022.65, y=71.00, z=-2201.11](shiken at -1022.6524717258154,71.0,-2201.108574465798), EntityPlayerMP['nika228'/503636, l='world', x=-68.80, y=83.22, z=203.12](nika228 at -68.80039560450076,83.21799606330502,203.11540022611877), EntityPlayerMP['3uM6oC'/508193, l='world', x=-1019.64, y=68.00, z=-1003.43](3uM6oC at -1019.6395819139298,68.0,-1003.4306854027401), EntityPlayerMP['bob0907'/537625, l='world', x=-2006.19, y=75.00, z=-195.24](bob0907 at -2006.19320614677,75.0,-195.23978129311493), EntityPlayerMP['ViGoR'/539665, l='world', x=-1554.54, y=65.00, z=-635.88](ViGoR at -1554.5390377828232,65.0,-635.8780926266733), EntityPlayerMP['Romaked'/548565, l='world', x=-2602.87, y=58.00, z=-1259.41](Romaked at -2602.870326763602,58.0,-1259.4120792010578), EntityPlayerMP['tibdog'/223959, l='world', x=-2660.82, y=71.00, z=-4844.72](tibdog at -2660.824165399409,71.0,-4844.720094327776), EntityPlayerMP['Black_Communist'/550553, l='world', x=-1014.95, y=71.00, z=-999.91](Black_Communist at -1014.9545733901476,71.0,-999.9134907591324), EntityPlayerMP['likema'/552260, l='world', x=-1502.91, y=70.00, z=-841.33](likema at -1502.9070122216842,70.0,-841.3260492450803), EntityPlayerMP['Moloko57'/554264, l='world', x=-5438.95, y=57.00, z=-105.30](Moloko57 at -5438.947618197499,57.0,-105.30000001192093), EntityPlayerMP['Bigmax'/554452, l='world', x=414.25, y=71.00, z=-640.96](Bigmax at 414.25433389844153,71.0,-640.9564666294019), EntityPlayerMP['LaZeR_SuPeR'/564077, l='world', x=-584.30, y=63.00, z=-620.93](LaZeR_SuPeR at -584.2976795027743,63.0,-620.9343547129248)]
    Chunk stats: ServerChunkCache: 1570 Drop: 0
    Level seed: 3395197471092354667
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-1001,79,-1001), Chunk: (at 7,4,7 in -63,-63; contains blocks -1008,0,-1008 to -993,255,-993), Region: (-2,-2; contains chunks -64,-64 to -33,-33, blocks -1024,0,-1024 to -513,255,-513)
    Level time: 57125171 game time, 57148068 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 17953 (now: true), thunder time: 4433 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:976)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:831)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:683)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Thermos Version: ca.tcpr:Thermos:1.7.10-1614.54
    Plugins: CoreProtect, Lockdown, WorldEdit, Playtime, NoServerMessages, ProSpam, OpenInv, RemoteToolkitPlugin, Essentials, AntiBugItem, AutoMessage, WorldBorder, EntityWatch, LevelHealth, MineBlocker, WorldGuard, AutoSaveWorld, KitAdder, EssentialsChat, PermissionsEx, WGExtender, MachineGuardReloaded, Vault, MyHome, EssentialsSpawn, MyWarp, GoreaRestrict, WGEnter, Scavenger, ShoppingCartReloaded, ProtocolLib, ColoredTags, ModFixNG, HolographicDisplays
    Disabled Plugins: 
    Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
    Java Version: 1.8.0_74, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 222920752 bytes (212 MB) / 1321205760 bytes (1260 MB) up to 8388608000 bytes (8000 MB)
    JVM Flags: 3 total; -Xms1024M -Xmx8000M -XX:+UseG1GC
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 47 mods loaded, 47 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](Thermos-1.7.10-1614-server.jar) 
    UCHIJAAAA   Forge{10.13.4.1614} [Minecraft Forge](Thermos-1.7.10-1614-server.jar) 
    UCHIJAAAA   kimagine{0.2} [KImagine](minecraft.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core](minecraft.jar) 
    UCHIJAAAA   Aroma1997Core{1.0.2.16} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHIJAAAA   ChocoPatcher{1.2} [Choco Patcher](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJAAAA   Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCHIJAAAA   IC2{2.2.820-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.820-experimental.jar) 
    UCHIJAAAA   AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels](AdvancedSolarPanel-1.7.10-3.5.1.jar) 
    UCHIJAAAA   appliedenergistics2{rv3-beta-6} [Applied Energistics 2](appliedenergistics2-rv3-beta-6.jar) 
    UCHIJAAAA   Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.1.2} [CoFH Core](CoFHCore-[1.7.10]3.1.2-325.jar) 
    UCHIJAAAA   BuildCraft|Core{7.1.16} [BuildCraft](buildcraft-7.1.16server.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.1.16} [BC Builders](buildcraft-7.1.16server.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.1.16} [BC Transport](buildcraft-7.1.16server.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.1.16} [BC Energy](buildcraft-7.1.16server.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.1.16} [BC Silicon](buildcraft-7.1.16server.jar) 
    UCHIJAAAA   BuildCraft|Robotics{7.1.16} [BC Robotics](buildcraft-7.1.16server.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.1.16} [BC Factory](buildcraft-7.1.16server.jar) 
    UCHIJAAAA   Forestry{4.2.12.60} [Forestry for Minecraft](forestry_1.7.10-4.2.12.60.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.4} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.4-114.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion](ThermalExpansion-[1.7.10]4.1.2-240.jar) 
    UCHIJAAAA   BuildCraft|Compat{7.1.5} [BuildCraft Compat](buildcraft-compat-7.1.5.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   chisel{2.9.4.CUSTOM} [Chisel](Chisel-2.9.4.CUSTOM.jar) 
    UCHIJAAAA   EventHelper{1.6} [EventHelper](EventHelper-1.6.jar) 
    UCHIJAAAA   GraviSuite{1.7.10-2.0.3} [Graviation Suite](GraviSuite-1.7.10-2.0.3server.jar) 
    UCHIJAAAA   IC2NuclearControl{2.4.0a} [Nuclear Control 2](IC2NuclearControl-2.4.0a.jar) 
    UCHIJAAAA   IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJAAAA   irontank{1.0.1 build @BUILD@} [Iron Tanks](irontank-1.7.10-1.0.1.50.jar) 
    UCHIJAAAA   MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10.jar) 
    UCHIJAAAA   Aroma1997sDimension{1.0} [Aroma1997's Dimensional World](miningworld.jar) 
    UCHIJAAAA   MrTJPCoreMod{1.1.0.33} [MrTJPCore](MrTJPCore-1.1.0.33-universal.jar) 
    UCHIJAAAA   ProjRed|Core{4.7.0pre12.95} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
    UCHIJAAAA   ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHIJAAAA   ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration](ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
    UCHIJAAAA   ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility](ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
    UCHIJAAAA   ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
    UCHIJAAAA   ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination](ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
    UCHIJAAAA   RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
    UCHIJAAAA   ThermalDynamics{1.7.10R1.2.0B2} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.2.0B2-169.jar) 
    UCHIJAAAA   TickProfiler{1.7.10} [TickProfiler](TickProfiler-1.7.10.39.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
    CoFHCore: -[1.7.10]3.1.2-325
    ThermalFoundation: -[1.7.10]1.2.4-114
    ThermalExpansion: -[1.7.10]4.1.2-240
    RedstoneArsenal: -[1.7.10]1.1.1-89
    ThermalDynamics: -[1.7.10]1.2.0B2-169
    Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
    Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Bukkit, Cauldron, or other Bukkit replacement
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 24 / 100; [EntityPlayerMP['AppleBoy'/6594, l='world', x=-1107.86, y=49.00, z=-2039.70](AppleBoy at -1107.8590525925608,49.0,-2039.699999988079), EntityPlayerMP['SupaBadazz'/6562, l='DIM-1', x=-96.59, y=42.88, z=-205.80](SupaBadazz at -96.5942150658143,42.875,-205.80072188669368), EntityPlayerMP['4Mir'/8596, l='world', x=-2630.21, y=72.00, z=-2618.50](4Mir at -2630.210238929766,72.0,-2618.5030594572454), EntityPlayerMP['Dominig12'/9741, l='world', x=-2649.29, y=69.00, z=-2641.32](Dominig12 at -2649.2880974628215,69.0,-2641.322918609913), EntityPlayerMP['oSlIk'/207409, l='world', x=-2646.26, y=76.00, z=-4822.92](oSlIk at -2646.258043963133,76.0,-4822.920616238591), EntityPlayerMP['tibdog'/223959, l='world', x=-2660.82, y=71.00, z=-4844.72](tibdog at -2660.824165399409,71.0,-4844.720094327776), EntityPlayerMP['veber'/389876, l='world', x=-2047.69, y=69.00, z=-1457.00](veber at -2047.6889925027995,69.0,-1457.0040799559047), EntityPlayerMP['DarkGuard'/395827, l='world', x=-2632.84, y=73.00, z=-2673.67](DarkGuard at -2632.840346960754,73.0,-2673.6660933952976), EntityPlayerMP['DJoniFX'/415459, l='world', x=-1774.65, y=70.00, z=-307.25](DJoniFX at -1774.6504534072867,70.0,-307.2541469054957), EntityPlayerMP['nistyak'/439307, l='world', x=-361.66, y=67.00, z=-373.83](nistyak at -361.6643500990588,67.0,-373.8302597416558), EntityPlayerMP['BoJI9'/468957, l='world', x=-1107.32, y=49.00, z=-2034.89](BoJI9 at -1107.3176942649088,49.0,-2034.8866930742633), EntityPlayerMP['shiken'/491653, l='world', x=-1022.65, y=71.00, z=-2201.11](shiken at -1022.6524717258154,71.0,-2201.108574465798), EntityPlayerMP['nika228'/503636, l='world', x=-68.80, y=83.22, z=203.12](nika228 at -68.80039560450076,83.21799606330502,203.11540022611877), EntityPlayerMP['3uM6oC'/508193, l='world', x=-1019.64, y=68.00, z=-1003.43](3uM6oC at -1019.6395819139298,68.0,-1003.4306854027401), EntityPlayerMP['bob0907'/537625, l='world', x=-2006.19, y=75.00, z=-195.24](bob0907 at -2006.19320614677,75.0,-195.23978129311493), EntityPlayerMP['ViGoR'/539665, l='world', x=-1554.54, y=65.00, z=-635.88](ViGoR at -1554.5390377828232,65.0,-635.8780926266733), EntityPlayerMP['Romaked'/548565, l='world', x=-2602.87, y=58.00, z=-1259.41](Romaked at -2602.870326763602,58.0,-1259.4120792010578), EntityPlayerMP['Black_Communist'/550553, l='world', x=-1014.95, y=71.00, z=-999.91](Black_Communist at -1014.9545733901476,71.0,-999.9134907591324), EntityPlayerMP['likema'/552260, l='world', x=-1502.91, y=70.00, z=-841.33](likema at -1502.9070122216842,70.0,-841.3260492450803), EntityPlayerMP['Moloko57'/554264, l='world', x=-5438.95, y=57.00, z=-105.30](Moloko57 at -5438.947618197499,57.0,-105.30000001192093), EntityPlayerMP['Bigmax'/554452, l='world', x=414.25, y=71.00, z=-640.96](Bigmax at 414.25433389844153,71.0,-640.9564666294019), EntityPlayerMP['LaZeR_SuPeR'/564077, l='world', x=-584.30, y=63.00, z=-620.93](LaZeR_SuPeR at -584.2976795027743,63.0,-620.9343547129248), EntityPlayerMP['peter_santana'/567014, l='DIM-1', x=441.01, y=88.00, z=-381.70](peter_santana at 441.0055605541669,88.0,-381.69999998807907), EntityPlayerMP['aRTILERIa1'/584557, l='DIM6', x=-341.43, y=80.00, z=-551.04](aRTILERIa1 at -341.4254734279413,80.0,-551.0407722294789)]
    Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by dmf444** [comment]
I'll take a look but we don't support bukkit/cauldron.
