### ISSUE TITLE
I add Russian translation 2.4.1a, 2.4.2a

### ISSUE THREAD

**Issue by lex1975** [xbony2/Nuclear-Control#169]
Sorry that I write here. I am not registered on the forum. This is not a bug report. Some new words from version 2.4.1a, 2.4.2a is not translated into Russian. I added a translation.
[ru_RU.zip](https://github.com/xbony2/Nuclear-Control/files/742434/ru_RU.zip)

**Comment by xbony2** [comment]
Спасибо
