### ISSUE TITLE
GTNH 2.0.2.7 Unable to load client after second launch when loading Nuclear Control 2

### ISSUE THREAD

**Issue by Lithorn** [xbony2/Nuclear-Control#177]
Just updated to 2.0.2.7 on GTNH, first launch worked fine. Forge loaded all mods without issue. Second attempt after relaunching client results in java hanging on loading Nuclear Control 2. Tested 3 times with each being a fresh install and all three had the same problem after the second launch.

Tested with latest java (8-161) reverted to older which worked previously on GTNH 2.0.1.3 (6-151) still had issue

Tested with nuclear control disabled in the Twitch mod loadup and the pack worked like a charm, loading to splash screen for playing. What changed between GTNH 2.0.1.3 Nuclear control and in 2.0.2.7 for the mod itself?

Using NC2 v 2.4.1a

**Comment by xbony2** [comment]
That's an outdated version of the mod. Maybe talk to the modpack maker first.

**Comment by Dream-Master** [comment]
@Lithorn i will update NC to newest version in the next update.

**Comment by Dream-Master** [comment]
@xbony2 not checking some mods for a long time because thought there are no new update available.

**Comment by xbony2** [comment]
I would recommend it for all of your mods. 2.4.1a was released on Jul 12, 2016, while 2.4.3a was released on Aug 14, 2017, so I would assume it's been a long time since you checked.

**Comment by Dream-Master** [comment]
I have the ic2 forum link which are not up to date. Curse link i never used before. @xbony2

**Comment by xbony2** [comment]
Fair enough I suppose.
