### ISSUE TITLE
Minor build issue

### ISSUE THREAD

**Issue by maggi373** [xbony2/Nuclear-Control#185]
The latest version 2.4.4a does not have it version set correctly
You can look on my fork https://github.com/Thorfusion/Nuclear-Control to save time.

![nuclearcontrol](https://user-images.githubusercontent.com/40539743/169712207-0b358d89-6383-4d1a-b48f-f13927c4295d.PNG)
.

**Comment by xbony2** [comment]
That's annoying. Where does it say `@VERSION@` in-game?

**Comment by maggi373** [comment]
the issue is inside the mcmod.info file. you find the @VERSION@ inside the mod settings
