### ISSUE TITLE
Include DragonAPI

### ISSUE THREAD

**Issue by xbony2** [xbony2/Nuclear-Control#188]
@maggi373 RotaryCraft won't load without so I can't test from the dev environment, even if it compiles and stuff (not that I plan to test much but still). Also for the files in `libs`, there should be a corresponding LICENSE file (like [LICENSE-BigReactors](https://github.com/xbony2/Nuclear-Control/blob/master/LICENSE-BigReactors)) for compliance reasons. Thanks a lot for help with this stuff.

**Comment by maggi373** [comment]
added the missing license, however i dont have a dedicated dev envirement, and i normally just test it with my modpack. i didnt encounter any issues with that it needed dragonapi. but my fork has it, so im adding it.

**Comment by maggi373** [comment]
wanted to note that i dont have rotarycraft nor dragonapi in my modpack
