### ISSUE TITLE
5x5 reactor support

### ISSUE THREAD

**Issue by xbony2** [xbony2/Nuclear-Control#45]

**Comment by xbony2** [comment]
Moving this to high for version 1.2+

**Comment by dmf444** [comment]
This is mainly for future reference.
4 main things that should be displayed on the screen:

Input tank fill level [getinputtank().getFluidAmount() / 10000 mB]
Output tank fill level [getoutputtank().getFluidAmount() / 10000 mB]
Heat Units per second [no get Func. must get variable, which is public]
Core Temperature [(getHeat() x 100) / getMaxHeat()]

As well, we could also display the input fluid cans and output cans. The stuff in square brackets are actual functions that can be called, and once I figure out how to get a block into the IC2 reactor system, this should all be a go!

**Comment by xbony2** [comment]
Nice :)

Getting the reactor to work with the thermal monitor is also a part of the support. Also with Thermometer, but hopefully that shouldn't be too difficult.
