### ISSUE TITLE
Render bug

### ISSUE THREAD

**Issue by xbony2** [xbony2/Nuclear-Control#52]
Several issues occur randomly with the Advanced Info Panel. It's texture can change into other blocks, other items, even entity textures. This bug has been reported previously, however I believed it was a mod conflict with Rei's Minimap, although it appears not to be so. Probably due to leak in something.

Picture: http://goo.gl/Yyv918

I'm not good with OpenGL at all, so all hands on deck.

Quote from Tahg: "xbony2, ok, it doesn't look like you bind a texture anywhere in ModelInfoPanel.drawFacing" "and the only place I see in renderScreen is at the very end"

**Comment by xbony2** [comment]
" when you have a Model you always need to be sure you have the texture bound first, there's nothing automatic for them" "if other TE's are drawing, you might get lucky and have it bound to something sensible"

**Comment by dmf444** [comment]
I started looking into this earlier, found no real solution, but I'll keep looking

**Comment by xbony2** [comment]
I think it's been fixed, or at least partially.

**Comment by dmf444** [comment]
This has only been partially fixed. Re-opening at a lower priority until fully resolved

**Comment by dmf444** [comment]
Again, I haven't seen a report of this happening, so i'll leave it open for a few more weeks, then close it

**Comment by xbony2** [comment]
I did though >.>

**Comment by dmf444** [comment]
In the last version?

**Comment by xbony2** [comment]
Yea.

**Comment by LanceShield** [comment]
I appear to be having this issue as well. I'm using 2.3.1a-Butt.

Screenshot: https://i.imgur.com/wPNlkGo.png

**Comment by BallisticChris** [comment]
Hm I am having the same problem with the minimap and nuclear control. I just use this mod for road signs when one day I log on and the rear textures have gone and been replaced with a transparent texture with weird pieces of wood dotted around. I restarted my whole minecraft window and it was fine. Everyone please try that. If not then it is probabyl a genuine bug but I had simular problems as you and restarting (closing minecraft, opening the launcher and reloading the mods) the game

**Comment by xbony2** [comment]
I haven't seen this in like forever, so...
