### ISSUE TITLE
remove sensors.modstats.org from your code

### ISSUE THREAD

**Issue by KellyMahan** [xbony2/Nuclear-Control#61]
Because this domain no longer exists and the nature of your code along with the way some operating systems failover dns requests our server at org.com was hit by a DDOS with requests for that domain.

Please make sure to notify users to upgrade their source as well.

**Comment by dmf444** [comment]
I believe that this was fixed, but I'll check into it later. Biggest problem right now is I think direwolf20 pack is still using an older version of NC2

**Comment by xbony2** [comment]
What DMF444 said. Modpack makers need to update their shit. There isn't anything that can be done about 1.7.2 Minecraft and before, but most people don't use that version so it should be fine.

I'm going to ask slowpoke to ask direwolf to update nuclear control, if that hasn't happened already.

**Comment by xbony2** [comment]
The current released version of the DW pack uses 2.0.5b-Unicorn, which is more or less six version behind (released in October 2014ish).
