### ISSUE TITLE
Missing Texture

### ISSUE THREAD

**Issue by VitorH** [xbony2/Nuclear-Control#62]
The texture **lamp4.png** can't be loaded. *Nuclear control 2.1.2a*.

![screenshot_13](https://cloud.githubusercontent.com/assets/2721565/6173829/ef2c935e-b2d1-11e4-957d-4d07e729cd6c.png)

**Comment by xbony2** [comment]
It's just a bit of console spam, no big deal.

**Comment by vigia122** [comment]
I won't reopen this issue, but a fix would be great, because exceptions are slow. Really slow.
