### ISSUE TITLE
Add CoFH as soft dependency

### ISSUE THREAD

**Issue by xbony2** [xbony2/Nuclear-Control#63]
(it's required for big reactors)

**Comment by Chocohead** [comment]
That doesn't mean if you're just using IC2 you still need it right?

**Comment by dmf444** [comment]
I don't think we need it as a soft dependency. If big reactors loads, then the instance has cofh. Else, big reactors will crash. Am I missing some thing?

**Comment by xbony2** [comment]
For Gradle for auto-installing stuff.

**Comment by dmf444** [comment]
Isn't big reactors dependency on the RF api? I thought that was it.

**Comment by xbony2** [comment]
Nope. It needs CoFHCore. [See](http://www.big-reactors.com/#/) the site.
