### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Xee1** [xbony2/Nuclear-Control#65]
Hi @xbony2 , with latest version of Nuclear Control(2.1.2a) I get this error, I think is BuildCraft.
http://pastebin.com/q79x9ydK
Buildcraft version: 6.3.7

**Comment by xbony2** [comment]
Uh... has anything happened, or is it just a console message?

**Comment by Xee1** [comment]
Console message, I did not notice anything strange for now, however, it seemed appropriate to report it.

**Comment by dmf444** [comment]
Something is calling the cross buildcraft, which won't work because we've deleted the TileEntity that controlled it (in favour of open RF). This won't crash or do anything wrong, but I'll fix it when I get the chance.

**Comment by Xee1** [comment]
Thanks!
