### ISSUE TITLE
Cross RF might break Counters

### ISSUE THREAD

**Issue by xbony2** [xbony2/Nuclear-Control#66]
[See](http://forum.industrial-craft.net/index.php?page=Thread&postID=181866#post181866)

**Comment by dmf444** [comment]
Not broken, just noticed I made a flaw in the code! When the blocks returns its TileEntity, it only checks to see if any other RF mod is installed. Thus, in a pack like direwolf's it will always show RF. If there is no RF capable mod installed, then it will show the EU and count properly. 

Further investigation is needed to check on how to avoid this

**Comment by dmf444** [comment]
Fixed in the last push ( 6350d5a0074edec3f3f5ac8413ece326a563b605 )
