### ISSUE TITLE
Update dependences

### ISSUE THREAD

**Issue by Xee1** [xbony2/Nuclear-Control#68]
Hi @xbony2 , If you try to build nuclear control with gradle, this error appear:

What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> Could not resolve cofh:CoFHCore:[1.7.10]3.0.0B9-40-dev.
  Required by:
      com.shedar.IC2NuclearControl:Nuclear-Control-master:2.1.2a
   > Could not GET 'https://libraries.minecraft.net/cofh/CoFHCore/%5B1.7.10%5D3.
0.0B9-40-dev/CoFHCore-%5B1.7.10%5D3.0.0B9-40-dev.pom'. Received status code 403
from server: Forbidden
   > Could not GET 'http://addons.cursecdn.com/files/2221/835/CoFHCore-%5B1.7.10
%5D3.0.0B9-40-dev.xml'.
      > org.apache.http.client.ClientProtocolException (no error message)
I think CoFHCore-B9 is very old.

**Comment by xbony2** [comment]
They probably removed it.

**Comment by xbony2** [comment]
Why are you trying to build it anyway?

**Comment by Xee1** [comment]
To test whether they were fixed some errors

**Comment by Xee1** [comment]
Thanks!
