### ISSUE TITLE
Overflow Error in Advanced Information Panel

### ISSUE THREAD

**Issue by janouna** [xbony2/Nuclear-Control#71]
I have an advanced information panel showing the fluid amount of a very large tank (~65 million mb).  Whenever it's filled more than about 30% (20 million fill, 45 million free), the fill percentage goes negative (starts at around -24%), and then starts counting up towards zero percent as the tank gets more full.  Seems like an overflow error in the division.

Nuclear Control version 2.1.2a
Minecraft version 1.7.10

**Comment by xbony2** [comment]
Upgrade to 2.2.0a if you can, although I don't think that will fix anything.

**Comment by xbony2** [comment]
Yo @janouna , is there any console information?

**Comment by janouna** [comment]
I just watched the percentage go negative, but the console didn't show anything.  I also looked through the console at startup but everything related to Nuclear Control looked normal (mostly registry adds).

**Comment by Speiger** [comment]
Reason for that is because you made a derp bug...
You incrment before you decrement. Which is at these high numbers not a good idea...
