### ISSUE TITLE
AE2 Stuff Textures

### ISSUE THREAD

**Issue by xbony2** [xbony2/Nuclear-Control#74]
Textures to make:
* [ ] ME Network Monitor. This is used to link the card with the AE network, like the [Reactor Monitor](http://ftb.gamepedia.com/Reactor_Monitor).
* [ ] Applied Energistics Monitor Kit.
* [ ] Applied Energistics Card.

I'm not entirely sure what the names of each file is, @dmf444 can probably assist in that. You can probably just name it something random.

I'm not sure what these textures would look like, so go wild. Well, not exactly wild, it should look NC2ish and AE2ish :P 

The Network Monitor can be either 16x16 or 32x32, although the kits/cards should be 32x32. Again, I'm not sure if the Network Monitor should be 16x16 or 32x32... since IC2 and IC2NC are usually 32x32 but AE2 is usually 16x16.

**Comment by Pyrolusite** [comment]
Alright, I'll work on it !

NC2 textures being 32x32 by default, I'd suggest using 32x32 for all this stuff.

**Comment by Pyrolusite** [comment]
Do we have any idea about the recipe, so that I can adapt these textures to reflect it ?

**Comment by xbony2** [comment]
There's not any recipe yet... I'll see if I can make something for you though in a minute or so.

**Comment by Pyrolusite** [comment]
Actually, I think I figured it out. It's supposed to be a block connected to AE cables, right ?

**Comment by xbony2** [comment]
Yes.

**Comment by xbony2** [comment]
[This](https://imgur.com/wimLDFS) is probably what the kit recipe will be. The dye would be the main color, I made it black since I wasn't really sure which color to make it (gray might look better, I dunno).

**Comment by xbony2** [comment]
[This](https://imgur.com/Y668eCR) is probably what the Monitor will be. Again, not definite.

**Comment by Pyrolusite** [comment]
Done. Create another issue if something went wrong.

**Comment by xbony2** [comment]
Looks good to me :) thanks!
