### ISSUE TITLE
Bug with IC2 Classic

### ISSUE THREAD

**Issue by Speiger** [xbony2/Nuclear-Control#75]
Well i mention it here but it is already known...

Your energy Counter & Average counter is backwards when you use IC2 Classic. Well it is only your machine that have that problem... And no other mods at all.
^^" Do not know why...
For the question if you can detect ic2 classic:
https://github.com/TinyModularThings/IC2Classic/blob/master/ic2/api/info/IC2Classic.java

**Comment by dmf444** [comment]
IC2 Classic is currently in development, bugs like this are bound to happen.

**Comment by Speiger** [comment]
@dmf444 i am the developer of IC2 Classic... Thats why i am Telling it...

**Comment by xbony2** [comment]
Checkout [this](https://github.com/xbony2/Nuclear-Control/tree/master/src/main/java/shedar/mods/ic2/nuclearcontrol/crossmod/ic2classic) btw, it's a cool lil' implementation of a IC2C detector.

**Comment by Speiger** [comment]
Yay i am a piece of code^^"
Just kidding. Your mod is already running with Classic just some bugs^^"

**Comment by Speiger** [comment]
And what do you mean with that? 
Especially with Speiger's terrible indent style

Sadly i am not able to translate it properly... And google/other translaters are not helping at all....

I guess its nothing good...

But your idea of how you made it with the detection is cool.
The difference between my version and yours is. You can detect my version/immbis version but you have no access to the Main IC2 file without having the mod importet.
My Version of detection provides the main class of the IC2 classic...
So that you can still use functions and co even if you are using only the api *_^

**Comment by Speiger** [comment]
But i see that your way is better...
Can i copy the way how you handled it so that people can easy detect which IC2 is loaded?
^^"

**Comment by xbony2** [comment]
The indent style refers to this:
```java
public class CompactWindmills implements SpmodMod
{
```
Over what I prefer:
```java
public class CompactWindmills implements SpmodMod{
```
(from https://github.com/TinyModularThings/TinyModularThings/blob/1.6.4/Spmod_Common/Source/speiger/src/compactWindmills/CompactWindmills.java)

Same thing with methods and such.

Anyway, for using code, you have to checkout the [license](https://github.com/xbony2/Nuclear-Control/blob/master/LICENSE). I can't change any conditions or anything.

It's the "New BSD License", aka the "Revised BSD License" aka the "Modified BSD License". You can google it and find more information in your preferred language.

**Comment by Speiger** [comment]
Well first coding style and permissions are not really required at all. That is only a to be nice thing. I would not even copy the code since my thinking what i would make is a little bit differend to yours...
In short: I was not asking to copy the code. I was asking to copy the idea to detect which ic2 is loaded^^"

So i assume that counts simply as yes.

**Comment by Speiger** [comment]
Ater reading that first part again i figured out what you mean about indnet style...
Well that indentstyle is what i can work the best with.... I do not like it to have everything so closed together... Since i am a person who see not really far that helps...

And a note at the end: this coding style is mostly inspired by SirSengir (Forestry), CovertJaguar (Railcraft), at some part IC2 1.2.5 or was it 1.1 do not remember right... And a lot of other people. I think Mushroom (the maker of Charging bench), was also another.
The reason of that is simply because i am a person who copies a lot, and that reaches from codingstyles up to personalities, you can not imagine how much flashbacks you get when you copy a lot of small parts from peoples personalities xD

**Comment by xbony2** [comment]
I like a more compact indent style since I look at stuff like brackets as invisible-. That's just me though.

**Comment by Speiger** [comment]
ok. 
I think coding styles are based on Preferences of the coder^^" But we should not say that a persion is bad because of that, but i kind a like your log prints

**Comment by Speiger** [comment]
ok here is the Result...
Thats the way i would have it done...
https://github.com/TinyModularThings/IC2Classic/blob/master/ic2/api/info/IC2Classic.java
That way you can way easier detect which ic2 is loaded

**Comment by Speiger** [comment]
Ran into the void
