### ISSUE TITLE
ME Network Monitor Breaks instantly with hand

### ISSUE THREAD

**Issue by dpsman917** [xbony2/Nuclear-Control#85]
Edit I simply did not know how to use the block Old post here http://paste.ee/p/iz5pE

However you really should still change the block durability to more than whatever it is because you can break it in survival mode with a bare hand within a millisecond and you don't get the block back.

TLDR; Make sure the ME Network monitor is on your storage network and you need an advanced panel that can support 2 cards for this to fully function. The other Applied energistics monitor kit has to be used on a crafting monitor to see crafting status.

Tested and confirmed it Cannot and Will not work though a sub-net.

The block is awesome however it does have some serious limitations.

Cannot be used across subnets. and AE2 is subnet city compared to ae1.
you can repeat an 8 channel ad-hoc storage network indefinitely only using 1 channel on the main network for the storage bus.

I usualy use more than 1 crafting storage per crafting network and you can only link to a single crafting monitor witch has to be part of the Crafting-storage/crafting-cocpu multiblock and the crafting monitor only shows whats being worked on in that specific crafting storage multiblock.

I can use multiple Info panels to get around this.

All in all its pretty balanced i guess, not super op all in one.

Useful if you dont have your crafting storages in a visable place none the less.

SShot of it working 
![new bitmap image 4](https://cloud.githubusercontent.com/assets/10163906/7741341/b508e832-ff4b-11e4-883b-ef8e954f2ee3.jpg)

**Comment by xbony2** [comment]
I blame DMF444.

**Comment by dpsman917** [comment]
lol Thanks for your response and Labels cant wait for this to be working properly ^.^

**Comment by dmf444** [comment]
For the item crafting to show, a card has to be clicked on a crafting monitor. The bytes problem concerns me, are your drives on another network?

**Comment by dmf444** [comment]
Also, I have not tested this with ME subnets, the block will scan through the current network, and I don't know how AE handles subnets.

**Comment by dpsman917** [comment]
Ahh thank you this needs to be documented somewhere as i could not find any info on how to use this block properly ill see if i can put it on the ftb wiki, yes my drives are on a subnet. going to test to see if i can get it working.

**Comment by dmf444** [comment]
Instant break problem has been fix for next release. Current documentation is my video, found here: http://youtu.be/AwlsDRljr1M

**Comment by xbony2** [comment]
I'll be adding to the wiki soon, currently just use DMF444's video.

**Comment by dpsman917** [comment]
awesome thanks for being such an awesome team you guys are the best! (i deal with really bad devs some times)
