### ISSUE TITLE
AE Monitor Kit is not minetweakable

### ISSUE THREAD

**Issue by JasonMcRay** [xbony2/Nuclear-Control#87]
Its the same issue as there was with BigReactors RF Reactor Kit. When I try to remove, or add my own recipe for the AE Monitor Kit via Minetweaker 3, I am getting that item doesn't exist.

Using: 2.2.5a

**Comment by xbony2** [comment]
Test comment

**Comment by xbony2** [comment]
Same reason I assume, it cannot modify stuff registered in postInit().

**Comment by dmf444** [comment]
Moved into init in last update, if problem persists, let us know

**Comment by JasonMcRay** [comment]
Sorry but I dont see download for the last update, so can't see if the problem is fixed or not.

**Comment by xbony2** [comment]
Not released yet. I'm having build issues, although dmf444 can pass a build version to me.
