### ISSUE TITLE
Nuclear Jetpack Support

### ISSUE THREAD

**Issue by Speiger** [xbony2/Nuclear-Control#91]
I recently added the Nuclear Jetpack to IC2 Classic,
Which is a Portable Nuclear Reactor, 
and the idea were that you can use the Nuclear Kit on that too.
What do you think about that?
I would write the code for that (if you do not want to write it)

**Comment by dmf444** [comment]
I'm just curious,if I'm wearing the jet pack, what would be the point of having the data put on a monitor?

**Comment by Speiger** [comment]
Do you always check your Jetpack when it has almost infinte fuel?
xD Also if someone else uses a nuclear jetpack in your base you can simply make a security system so that he shutof all parts ofyou base if someone has a Overheating Nuclear Jetpack on their Armor slots...

**Comment by xbony2** [comment]
I don't really see how a card can easily monitor an item in someone's inventory, so I'm rejecting this idea, sorry.

Btw, who's crazy idea is it to strap a nuclear reactor on your back?

**Comment by Speiger** [comment]
Well i have it from the IC2 Wiki and if i am not wrong the Original Dev would have implemented it if he not left... So now it exsists in Classic and You have a Nuclear Jetpack now xDDD

**Comment by xbony2** [comment]
Germans :P

**Comment by Speiger** [comment]
Well i made it but the request came from a none german guy. xDD And i think other people use it too.
Chocohead and Mine_Sasha are using it xDD
