### ISSUE TITLE
Allow Older Forge Compatability

### ISSUE THREAD

**Issue by Chocohead** [xbony2/Nuclear-Control#94]
If you replace the "storage.fluid.getFluidID()" calls with "storage.fluid.getFluid().getID()", that should allow pre-fluid change forge versions to work as well as keeping the post-fluid change ones working. I'd make a pull request myself but I'm not sure if you've added any more newer Forge dependencies.

**Comment by xbony2** [comment]
Test

**Comment by xbony2** [comment]
We're probably going to push users to use the (new) recommend Forge, so...

**Comment by Chocohead** [comment]
(╯°□°）╯︵ ┻━┻
